### ISSUE TITLE
Does Madrona support more than 256 environments running in parallel on a GPU?

### ISSUE THREAD

**Issue by 2019cyf** [shacklettbp/madrona#44]
When more than 256 environments run in parallel on a GPU, read and write operations become disordered. Why is this happening?I have confirmed that the sizes of the exported variables are accurate and that the export IDs are correct. I only changed the variables to be exported in the ActionSystem, but when I printed the results on the Python side, they were messed up.

**Comment by shacklettbp** [comment]
Madrona does support more than 256 environments. One possibility is that you have a race condition in your code, and you're only seeing it manifest when the number of system invocations is larger than a single GPU thread block (256 threads). There is some internal synchronization on the threadblock level that could be masking a race condition if your system only runs on 1 threadblock.

Happy to help more if you have more details about your exact setup.

**Comment by 2019cyf** [comment]
Thank you for your help. In the code of sim, we assign different values to each agent in the actionSystem function, as shown in the figure below. When we run more than 256 environments on the Python side, we detect that the obs on each agent does not meet our expectations.
![image](https://github.com/user-attachments/assets/3d1390b8-2df6-4d10-8b08-8dbdfc7944e4)
![image](https://github.com/user-attachments/assets/e50041f4-993e-4baa-ac49-87639f68fe30)
![image](https://github.com/user-attachments/assets/028307f2-89ca-40d7-981d-07d91d3615b9)

**Comment by 2019cyf** [comment]
I'm sorry, I forgot to mention this: obs is part of the agent.
![image](https://github.com/user-attachments/assets/70999189-a06d-4d73-bf65-e1e9f402a9b1)

**Comment by 2019cyf** [comment]
I seem to have addressed the problem. It's because the component memory is not contiguous. Values need to be got based on the agent and world ID. Thank you for your help.

**Comment by shacklettbp** [comment]
Ah, you likely are missing a call to sort that component array somewhere. Check the escape room escape for the "queueSortByWorld" template function that's used in GPU mode.

**Comment by shacklettbp** [comment]
https://github.com/shacklettbp/madrona_escape_room/blob/main/src/sim.cpp#L718

**Comment by shacklettbp** [comment]
After the sort is applied it should all be contiguous and grouped by world ID.

**Comment by 2019cyf** [comment]
ok, thank you for your help
